import type { ReactNode } from "react";

export default function Page(): ReactNode {
  return (
    <div className="min-h-screen bg-linear-to-b from-gray-50 to-gray-200 py-16 flex items-center justify-center">
      <div className="relative bg-white max-w-4xl mx-4 w-full border-10 border-gray-800 rounded-xl shadow-[0_0_60px_rgba(0,0,0,0.1)] p-10">
        <div className="absolute inset-3 border-[3px] border-gray-500 rounded-lg pointer-events-none" />

        <h1 className="text-4xl font-serif text-gray-900 mb-8 text-center uppercase tracking-wide">Disclaimer</h1>

        <div className="space-y-8 text-gray-800 leading-relaxed max-w-2xl mx-auto">
          <p>
            The information and insights provided through Social Commerce Accountants Ltd (&quot;SCA&quot;) and its
            software platform (SCAi) are for informational purposes only. While we take reasonable steps to ensure
            accuracy, the outputs, reports, and analytics generated by the platform:
          </p>

          <ul className="list-disc pl-6 space-y-2">
            <li>Do not constitute legal, financial, accounting, or tax advice.</li>
            <li>Should not be relied upon as a substitute for professional judgment.</li>
            <li>May be affected by limitations of third-party APIs, data availability, or user inputs.</li>
          </ul>

          <p>
            SCA makes no warranties or guarantees, express or implied, regarding the accuracy, completeness, or
            reliability of any data presented through the Services. You remain solely responsible for reviewing your
            financial information, complying with applicable laws, and making business or tax decisions.
          </p>

          <p>
            To the fullest extent permitted by law, SCA disclaims liability for any loss or damage arising from reliance
            on information generated by the Services.
          </p>

          <p className="font-medium">For professional accounting or tax advice, please consult a qualified adviser.</p>
        </div>

        <div className="mt-12 text-center text-gray-700 italic text-sm">
          <p>Issued by Social Commerce Accountants Ltd • Protecting Your Data with Integrity</p>
          <div className="mt-2 border-t border-gray-600 w-40 mx-auto" />
        </div>
      </div>
    </div>
  );
}
